# SPDX-License-Identifier: Apache-2.0

load("@rules_go//go:def.bzl", "go_library", "go_test")

package(default_visibility = ["//visibility:public"])

go_library(
    name = "protocol",
    srcs = [
        "protocol.go",
    ],
    importpath = "github.com/tap-dev/tap/pkg/protocol",
    deps = [
        "//pkg/protocol/generated",
    ],
)

go_test(
    name = "protocol_test",
    srcs = [
        "conformance_test.go",
        "protocol_test.go",
    ],
    data = [
        "//protocol/conformance:fixtures",
        "//protocol/conformance:version",
        "//protocol/schemas:generated_schemas",
    ],
    embed = [":protocol"],
    deps = [
        "@com_github_santhosh_tekuri_jsonschema_v6//:jsonschema",
    ],
)
