#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Driver for the TAP codegen pipeline. Invoked via `bazel run //tools/codegen:generate`.
#
# Reads CUE schemas under protocol/schemas/, produces:
#   - protocol/schemas/_generated/all.json   (intermediate JSON Schema, one combined doc)
#   - crates/tap-protocol/src/generated/all.rs  (Rust, via cargo-typify)
#   - packages/tap-protocol/src/generated/all.ts  (TypeScript, via json-schema-to-typescript)
#   - pkg/protocol/generated/*.go            (Go, via cue exp gengotypes — one file per .cue file)
#
# Why a single combined JSON Schema instead of per-file:
#   CUE definitions can reference siblings in the same package (e.g.,
#   agent_register.cue uses identity#DeveloperId). Per-file `cue export`
#   doesn't pull siblings, and CUE's expression evaluator on the CLI cannot
#   bind to `#Foo` references directly. The pipeline emits a single
#   `$defs`-rooted document that each conformance runner indexes by
#   definition name.
#
# Bazel sets BUILD_WORKSPACE_DIRECTORY when invoked through `bazel run`.
# Outside Bazel, fall back to the script's parent-of-parent directory.

set -euo pipefail

REPO_ROOT="${BUILD_WORKSPACE_DIRECTORY:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "${REPO_ROOT}"

SCHEMAS_DIR="protocol/schemas"
JSON_SCHEMA_DIR="${SCHEMAS_DIR}/_generated"
RUST_OUT_DIR="crates/tap-protocol/src/generated"
TS_OUT_DIR="packages/tap-protocol/src/generated"
GO_OUT_DIR="pkg/protocol/generated"

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required tool '$1' not on PATH. See tools/codegen/README.md." >&2
    exit 1
  fi
}

require_tool cue
require_tool cargo
require_tool json2ts

mkdir -p "${JSON_SCHEMA_DIR}" "${RUST_OUT_DIR}" "${TS_OUT_DIR}" "${GO_OUT_DIR}"

# --- 1. CUE → JSON Schema -------------------------------------------------
# One combined document keyed by `$defs["Foo"]` for each definition reachable
# from CodegenRoot in protocol/schemas/codegen_export.cue. CUE emits `#Foo`
# keys and `%23Foo` refs (URL-encoded `#`); we normalize both to plain `Foo`
# so downstream codegen tools (cargo-typify, json-schema-to-typescript) and
# the conformance runners can resolve them.
echo "▸ CUE → JSON Schema (combined)"
cue def --out=jsonschema -e CodegenRoot "./${SCHEMAS_DIR}" \
  > "${JSON_SCHEMA_DIR}/all.cue.json"

python3 - <<PYEOF
import json
src = open("${JSON_SCHEMA_DIR}/all.cue.json").read()
# Rename \$defs keys: "#Foo" -> "Foo"
doc = json.loads(src)
defs = doc.get("\$defs", {})
renamed = {}
for k, v in defs.items():
    renamed[k.lstrip("#")] = v
doc["\$defs"] = renamed
out = json.dumps(doc, indent=2, sort_keys=True)
# Rewrite \$ref strings: "#/\$defs/%23Foo" -> "#/\$defs/Foo"
out = out.replace("#/\$defs/%23", "#/\$defs/")
open("${JSON_SCHEMA_DIR}/all.json", "w").write(out + "\n")
PYEOF
rm "${JSON_SCHEMA_DIR}/all.cue.json"

# --- 2. JSON Schema → Rust (cargo-typify) ---------------------------------
# Best-effort: cargo-typify v0.6.2 panics on certain CUE-emitted constructs
# (`allOf` + `not` patterns from the FilePath/BranchName regexes, the type-
# narrowing `allOf: [{number}, {integer}]` for LineNumber/TtlSeconds).
# Phase 1 conformance does not require Rust generated types — the runner
# validates against the JSON Schema directly. Skip the step gracefully if
# typify fails; mod.rs ships an empty module so the crate still compiles.
echo "▸ JSON Schema → Rust"
typify_log=$(mktemp)
if cargo typify --output "${RUST_OUT_DIR}/all.rs" "${JSON_SCHEMA_DIR}/all.json" >"${typify_log}" 2>&1; then
  cat > "${RUST_OUT_DIR}/mod.rs" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
// @generated by tools/codegen/generate.sh — DO NOT EDIT.
pub mod all;
pub use all::*;
EOF
  echo "  ✓ generated"
else
  echo "  ⚠ cargo-typify failed; emitting empty stub (see typify_log for details):"
  head -5 "${typify_log}" | sed 's/^/    /'
  rm -f "${RUST_OUT_DIR}/all.rs"
  cat > "${RUST_OUT_DIR}/mod.rs" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
// @generated by tools/codegen/generate.sh — DO NOT EDIT.
//
// Rust binding generation is currently disabled because cargo-typify v0.6.2
// panics on the CUE-emitted JSON Schema (specifically, `allOf` containing
// `not`-patterns from #FilePath / #BranchName regex constraints and the
// type-narrowing `allOf` for #LineNumber / #TtlSeconds). The conformance
// runner validates against the JSON Schema directly, so generated Rust
// types are not on the critical path for Phase 1. Tracked in
// project-context.md §9.6.
EOF
fi
rm -f "${typify_log}"

# --- 3. JSON Schema → TypeScript (json-schema-to-typescript) -------------
echo "▸ JSON Schema → TypeScript"
json2ts \
  --input "${JSON_SCHEMA_DIR}/all.json" \
  --output "${TS_OUT_DIR}/all.ts" \
  --bannerComment "/* SPDX-License-Identifier: Apache-2.0 */
/* @generated by tools/codegen/generate.sh — DO NOT EDIT. */"

cat > "${TS_OUT_DIR}/index.ts" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
// @generated by tools/codegen/generate.sh — DO NOT EDIT.
export * from "./all.js";
EOF

# --- 4. CUE → Go (cue exp gengotypes) -------------------------------------
# `cue exp gengotypes` writes one combined `cue_types_gen.go` next to the
# .cue files, with `package schemas`. Relocate it to the canonical
# pkg/protocol/generated/ directory and rename the package so it matches the
# import path `github.com/tap-dev/tap/pkg/protocol/generated`.
echo "▸ CUE → Go"
( cd "${SCHEMAS_DIR}" && cue exp gengotypes . )
src="${SCHEMAS_DIR}/cue_types_gen.go"
dest="${GO_OUT_DIR}/types.go"
if [ -f "${src}" ]; then
  # Replace package declaration. sed on macOS requires '' for in-place no-backup.
  sed -e 's/^package schemas$/package generated/' "${src}" > "${dest}"
  rm -f "${src}"
  echo "  - $(basename "${dest}")"
else
  echo "  ⚠ cue exp gengotypes produced no output"
fi

echo "✓ codegen complete"
