#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Driver for the TAP codegen pipeline. Invoked via `bazel run //tools/codegen:generate`.
#
# Reads CUE schemas under protocol/schemas/, produces:
#   - protocol/schemas/_generated/*.json   (intermediate JSON Schema)
#   - crates/tap-protocol/src/generated/   (Rust, via typify)
#   - packages/tap-protocol/src/generated/ (TypeScript, via json-schema-to-typescript)
#   - pkg/protocol/generated/              (Go, via cue exp gengotypes)
#
# Bazel sets BUILD_WORKSPACE_DIRECTORY when invoked through `bazel run`. Outside
# Bazel, fall back to the script's parent-of-parent directory.

set -euo pipefail

REPO_ROOT="${BUILD_WORKSPACE_DIRECTORY:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
cd "${REPO_ROOT}"

SCHEMAS_DIR="protocol/schemas"
JSON_SCHEMA_DIR="${SCHEMAS_DIR}/_generated"
RUST_OUT_DIR="crates/tap-protocol/src/generated"
TS_OUT_DIR="packages/tap-protocol/src/generated"
GO_OUT_DIR="pkg/protocol/generated"

# Schemas to generate bindings for. Append new entries when adding messages.
SCHEMAS=(
  "envelope"
  "identity"
  "agent_register"
)

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "error: required tool '$1' not on PATH. See tools/codegen/README.md." >&2
    exit 1
  fi
}

require_tool cue
require_tool typify
require_tool json2ts

mkdir -p "${JSON_SCHEMA_DIR}" "${RUST_OUT_DIR}" "${TS_OUT_DIR}" "${GO_OUT_DIR}"

# --- 1. CUE → JSON Schema -------------------------------------------------
echo "▸ CUE → JSON Schema"
for schema in "${SCHEMAS[@]}"; do
  echo "  - ${schema}"
  cue export \
    --out=jsonschema \
    --outfile="${JSON_SCHEMA_DIR}/${schema}.json" \
    --force \
    "${SCHEMAS_DIR}/${schema}.cue"
done

# --- 2. JSON Schema → Rust (typify) ---------------------------------------
echo "▸ JSON Schema → Rust"
for schema in "${SCHEMAS[@]}"; do
  echo "  - ${schema}"
  typify \
    --output "${RUST_OUT_DIR}/${schema}.rs" \
    "${JSON_SCHEMA_DIR}/${schema}.json"
done

# Re-export module
cat > "${RUST_OUT_DIR}/mod.rs" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
// @generated by tools/codegen/generate.sh — DO NOT EDIT.
EOF
for schema in "${SCHEMAS[@]}"; do
  echo "pub mod ${schema};" >> "${RUST_OUT_DIR}/mod.rs"
done

# --- 3. JSON Schema → TypeScript (json-schema-to-typescript) -------------
echo "▸ JSON Schema → TypeScript"
for schema in "${SCHEMAS[@]}"; do
  echo "  - ${schema}"
  json2ts \
    --input "${JSON_SCHEMA_DIR}/${schema}.json" \
    --output "${TS_OUT_DIR}/${schema}.ts" \
    --bannerComment "/* SPDX-License-Identifier: Apache-2.0 */
/* @generated by tools/codegen/generate.sh — DO NOT EDIT. */"
done

# Re-export barrel
cat > "${TS_OUT_DIR}/index.ts" <<'EOF'
// SPDX-License-Identifier: Apache-2.0
// @generated by tools/codegen/generate.sh — DO NOT EDIT.
EOF
for schema in "${SCHEMAS[@]}"; do
  echo "export * from \"./${schema}\";" >> "${TS_OUT_DIR}/index.ts"
done

# --- 4. CUE → Go (cue exp gengotypes) -------------------------------------
echo "▸ CUE → Go"
( cd "${SCHEMAS_DIR}" && cue exp gengotypes . )
# gengotypes writes alongside the .cue files; relocate to the canonical
# generated directory.
find "${SCHEMAS_DIR}" -maxdepth 1 -name "*_go_gen.go" -print0 | while IFS= read -r -d '' f; do
  base="$(basename "${f}" _go_gen.go)"
  dest="${GO_OUT_DIR}/${base}.go"
  mv "${f}" "${dest}"
  echo "  - ${base}.go"
done

echo "✓ codegen complete"
